gems:
  - jemoji
  - jekyll-sitemap

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:          /:categories/:year/:month/:title/

# Setup
title:            PixelZFameBot
tagline:          'Development Blog'
description:      'Development Blog for PixelZFameBot'

author:
  name:           'PixelZerg'
  url:            'https://pixelzerg.github.io'

paginate:         10

# Custom vars
version:          '0.0.2 Alpha'

url: https://pixelzerg.github.io/PixelZFameBotInfo
domain: pixelzerg.github.io/PixelZFameBot

releasenote: "Closed beta testing will begin in the near future."