# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:          /:categories/:year/:month/:title/

# Setup
title:            PixelZFameBot
tagline:          'Development Blog'
description:      'Development Blog for PixelZFameBot'

author:
  name:           'PixelZerg'
  url:            'https://pixelzerg.github.io'

paginate:         5

# Custom vars
version:          '0.0.1 Alpha'

url: https://pixelzerg.github.io/PixelZFameBotInfo
domain: pixelzerg.github.io/PixelZFameBot

releasedate: "1-2 weeks"